/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DengXian_22.c                                         *
* Font:        ?? Light                                            *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Read pattern file: C:\Users\admin\Desktop\1.txt                    *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\admin\Desktop\1.txt                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDengXian_22;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_002B[ 20] = { /* code 002B, PLUS SIGN */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_002E[  1] = { /* code 002E, FULL STOP */
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0030[ 30] = { /* code 0030, DIGIT ZERO */
  __XXXXX_,________,
  _XX___XX,________,
  _X_____X,________,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X______X,X_______,
  _X_____X,________,
  _XX___XX,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0031[ 15] = { /* code 0031, DIGIT ONE */
  ___XX___,
  _XX_X___,
  X___X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0032[ 15] = { /* code 0032, DIGIT TWO */
  __XXXX__,
  _X____X_,
  XX_____X,
  X______X,
  _______X,
  _______X,
  ______X_,
  _____X__,
  ____XX__,
  ___XX___,
  __X_____,
  __X_____,
  _X______,
  X_______,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0033[ 30] = { /* code 0033, DIGIT THREE */
  __XXXXX_,________,
  _X_____X,________,
  XX______,X_______,
  X_______,X_______,
  ________,X_______,
  ________,X_______,
  ______XX,________,
  ___XXXX_,________,
  _______X,________,
  ________,X_______,
  ________,X_______,
  X_______,X_______,
  X_______,X_______,
  _X_____X,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0034[ 30] = { /* code 0034, DIGIT FOUR */
  ______X_,________,
  _____XX_,________,
  _____XX_,________,
  ____X_X_,________,
  ___X__X_,________,
  ___X__X_,________,
  __X___X_,________,
  __X___X_,________,
  _X____X_,________,
  X_____X_,________,
  XXXXXXXX,X_______,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0035[ 30] = { /* code 0035, DIGIT FIVE */
  XXXXXXXX,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_XXXXX_,________,
  XX____XX,________,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  X______X,X_______,
  _X_____X,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0036[ 30] = { /* code 0036, DIGIT SIX */
  ___XXXX_,________,
  __X____X,________,
  _X______,X_______,
  _X______,________,
  X_______,________,
  X_______,________,
  X__XXXX_,________,
  XXX____X,________,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  _X_____X,X_______,
  _XX___XX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0037[ 30] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,X_______,
  ________,X_______,
  _______X,________,
  ______X_,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ___X____,________,
  ___X____,________,
  ___X____,________,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0038[ 30] = { /* code 0038, DIGIT EIGHT */
  __XXXXX_,________,
  _X_____X,________,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  _X_____X,________,
  __XXXXX_,________,
  _X_____X,________,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  _X_____X,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0039[ 30] = { /* code 0039, DIGIT NINE */
  __XXXX__,________,
  _XX___XX,________,
  XX_____X,________,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  XX_____X,X_______,
  _XX___X_,X_______,
  __XXXX__,X_______,
  ________,X_______,
  _______X,________,
  X______X,________,
  _X____X_,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_003E[ 20] = { /* code 003E, GREATER-THAN SIGN */
  X_______,________,
  _XX_____,________,
  ___XXX__,________,
  ______XX,________,
  ________,XX______,
  ________,XX______,
  ______XX,________,
  ___XXX__,________,
  _XX_____,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0041[ 30] = { /* code 0041, LATIN CAPITAL LETTER A */
  ______X_,________,
  _____X_X,________,
  _____X_X,________,
  _____X_X,X_______,
  ____X___,X_______,
  ____X___,X_______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  __XXXXXX,XXX_____,
  __X_____,__X_____,
  _X______,___X____,
  _X______,___X____,
  _X______,___X____,
  X_______,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0042[ 30] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXX__,________,
  X_____X_,________,
  X______X,________,
  X______X,________,
  X______X,________,
  X______X,________,
  X_____X_,________,
  XXXXXX__,________,
  X_____XX,________,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_____XX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0043[ 30] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,X_______,
  __XX____,XX______,
  _XX_____,__X_____,
  _X______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  _X______,__X_____,
  _X______,_X______,
  __XX____,XX______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0044[ 30] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  X______X,X_______,
  X_______,XX______,
  X_______,_X______,
  X_______,__X_____,
  X_______,__X_____,
  X_______,__X_____,
  X_______,__X_____,
  X_______,__X_____,
  X_______,__X_____,
  X_______,_XX_____,
  X_______,_X______,
  X_______,X_______,
  X______X,X_______,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0045[ 15] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXXXX_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_004C[ 15] = { /* code 004C, LATIN CAPITAL LETTER L */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_004E[ 30] = { /* code 004E, LATIN CAPITAL LETTER N */
  X_______,__X_____,
  XX______,__X_____,
  X_X_____,__X_____,
  X_X_____,__X_____,
  X__X____,__X_____,
  X___X___,__X_____,
  X___X___,__X_____,
  X____X__,__X_____,
  X_____X_,__X_____,
  X_____X_,__X_____,
  X______X,__X_____,
  X_______,X_X_____,
  X_______,X_X_____,
  X_______,_XX_____,
  X_______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0051[ 38] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ____XXXX,XX______,
  __XX____,__XX____,
  _XX_____,___XX___,
  _X______,____X___,
  X_______,_____X__,
  X_______,_____X__,
  X_______,_____X__,
  X_______,_____X__,
  X_______,_____X__,
  X_______,_____X__,
  XX______,_____X__,
  _X______,____X___,
  __X_____,___XX___,
  ___X____,__XX____,
  ____XXXX,XX______,
  _______X,________,
  ________,X_______,
  ________,X_______,
  ________,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0053[ 15] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXX__,
  _X____X_,
  X______X,
  X_______,
  X_______,
  XX______,
  _XX_____,
  ___XXX__,
  ______X_,
  _______X,
  _______X,
  X______X,
  X______X,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0055[ 30] = { /* code 0055, LATIN CAPITAL LETTER U */
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  _X______,X_______,
  _XX____X,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0056[ 30] = { /* code 0056, LATIN CAPITAL LETTER V */
  X_______,___X____,
  _X______,__X_____,
  _X______,__X_____,
  _X______,__X_____,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ____X__X,________,
  ____X__X,________,
  ____X_X_,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_0075[ 11] = { /* code 0075, LATIN SMALL LETTER U */
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  X_____XX,
  _X___XXX,
  __XXXX_X};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_00D7[ 18] = { /* code 00D7, MULTIPLICATION SIGN */
  ________,________,
  _X_____X,________,
  __X___X_,________,
  ___X_X__,________,
  ____X___,________,
  ___X_X__,________,
  __X___X_,________,
  _X_____X,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_4E2D[ 38] = { /* code 4E2D */
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  X______X,______X_,
  X______X,______X_,
  X______X,______X_,
  X______X,______X_,
  X______X,______X_,
  X______X,______X_,
  XXXXXXXX,XXXXXXX_,
  X______X,______X_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_51C6[ 57] = { /* code 51C6 */
  ________,X___X___,________,
  ________,X___XX__,________,
  _X_____X,_____X__,________,
  __X____X,______X_,________,
  ___X__XX,XXXXXXXX,XX______,
  ______XX,____X___,________,
  _____X_X,____X___,________,
  ____X__X,XXXXXXXX,X_______,
  ____X__X,____X___,________,
  ____X__X,____X___,________,
  ___X___X,____X___,________,
  __X____X,____X___,________,
  __X____X,XXXXXXXX,X_______,
  _X_____X,____X___,________,
  XX_____X,____X___,________,
  X______X,____X___,________,
  _______X,XXXXXXXX,XXX_____,
  _______X,________,________,
  _______X,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_52A8[ 60] = { /* code 52A8 */
  ________,_____X__,________,
  ________,_____X__,________,
  _XXXXXXX,X____X__,________,
  ________,_____X__,________,
  ________,_____X__,________,
  ________,_XXXXXXX,XX______,
  ________,_____X__,_X______,
  ________,_____X__,_X______,
  XXXXXXXX,XX___X__,_X______,
  ____X___,_____X__,_X______,
  ____X___,_____X__,_X______,
  ___X__X_,____X___,_X______,
  ___X___X,____X___,_X______,
  ___X____,X___X___,_X______,
  __X_____,X___X___,_X______,
  _X___XXX,XX_X____,_X______,
  _XXXX___,_X_X____,_X______,
  ________,__X_____,_X______,
  ________,_X____XX,X_______,
  ________,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_53C2[ 60] = { /* code 53C2 */
  ________,_X______,________,
  ________,XX______,________,
  _______X,X___XX__,________,
  ______XX,______X_,________,
  _____X__,_______X,________,
  ____XXXX,XXXXXXX_,X_______,
  ________,_X______,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _______X,_____X__,________,
  ______X_,___X__X_,________,
  _____X__,_XX____X,________,
  ___XX__X,X____X__,XX______,
  _XX__XX_,____X___,X_XX____,
  _X______,__XX___X,X_______,
  _______X,XX____X_,________,
  ______X_,____XX__,________,
  ________,__XX____,________,
  _______X,XX______,________,
  ____XXX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_56DE[ 34] = { /* code 56DE */
  XXXXXXXX,XXXXXXX_,
  X_______,______X_,
  X_______,______X_,
  X_______,______X_,
  X___XXXX,XXX___X_,
  X___X___,__X___X_,
  X___X___,__X___X_,
  X___X___,__X___X_,
  X___X___,__X___X_,
  X___X___,__X___X_,
  X___XXXX,XXX___X_,
  X_______,______X_,
  X_______,______X_,
  X_______,______X_,
  XXXXXXXX,XXXXXXX_,
  X_______,______X_,
  X_______,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_5E8F[ 57] = { /* code 5E8F */
  ________,_X______,________,
  ________,_XX_____,________,
  ________,___X____,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  __X_____,________,________,
  __X_____,________,________,
  __X___XX,XXXXXXXX,________,
  __X_____,______X_,________,
  __X_____,XXX_XX__,________,
  __X_____,___XX___,________,
  __X__XXX,XXXXXXXX,XXX_____,
  __X_____,___X____,_X______,
  __X_____,___X____,_X______,
  __X_____,___X____,X_______,
  __X_____,___X____,________,
  __X_____,___X____,________,
  _X______,___X____,________,
  _X______,___X____,________,
  X_______,_XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_5F0F[ 57] = { /* code 5F0F */
  ________,___X____,________,
  ________,___X__X_,________,
  ________,___X___X,________,
  ________,___X____,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  __XXXXXX,XXX_X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,_____X__,________,
  _____X__,_____X__,________,
  _____X__,XXX__X__,________,
  _XXXXXXX,______X_,__X_____,
  ________,_______X,_X______,
  ________,_______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_624B[ 57] = { /* code 624B */
  ________,______XX,________,
  __XXXXXX,XXXXXX__,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ___XXXXX,XXXXXXXX,X_______,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  XXXXXXXX,XXXXXXXX,XXX_____,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  _______X,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_62E9[ 57] = { /* code 62E9 */
  ___X____,________,________,
  ___X___X,XXXXXXXX,X_______,
  ___X____,_X_____X,________,
  ___X____,_X_____X,________,
  XXXXXXX_,__X___X_,________,
  ___X____,___X_X__,________,
  ___X____,___XX___,________,
  ___X__X_,__X_XXXX,________,
  ___X_X__,XX__X___,XXX_____,
  ___XX__X,____X___,________,
  __XX____,XXXXXXXX,X_______,
  XX_X____,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X__XX,XXXXXXXX,XXX_____,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  __X_____,____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_6821[ 57] = { /* code 6821 */
  ___X____,___X____,________,
  ___X____,____X___,________,
  ___X____,_____X__,________,
  ___X____,XXXXXXXX,XXX_____,
  XXXXXXX_,________,________,
  ___X____,___X____,________,
  ___X____,__X____X,________,
  __X_X___,_X______,XX______,
  __XX_X__,XX______,_X______,
  __XX__X_,X_X____X,________,
  _X_X____,__X____X,________,
  X__X____,__X___X_,________,
  X__X____,___X__X_,________,
  ___X____,____XX__,________,
  ___X____,____XX__,________,
  ___X____,____XX__,________,
  ___X____,__XX__XX,________,
  ___X____,XX______,XXX_____,
  ___X___X,________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_6A21[ 57] = { /* code 6A21 */
  ____X___,___X___X,________,
  ____X___,___X___X,________,
  ____X___,XXXXXXXX,XXXX____,
  ____X___,___X___X,________,
  _XXXXXXX,_XXXXXXX,XX______,
  ____X___,_X______,_X______,
  ____X___,_X______,_X______,
  ___XXX__,_XXXXXXX,XX______,
  ___XX_X_,_X______,_X______,
  __X_X__X,_X______,_X______,
  __X_X___,_XXXXXXX,XX______,
  _X__X___,_____X__,________,
  _X__X___,_____X__,________,
  ____X__X,XXXXXXXX,XXXX____,
  ____X___,____X_X_,________,
  ____X___,____X__X,________,
  ____X___,___X____,X_______,
  ____X___,_XX_____,_XXX____,
  ____X__X,X_______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_6D41[ 57] = { /* code 6D41 */
  ________,__X_____,________,
  __X_____,___XX___,________,
  ___X____,____X___,________,
  ____X_XX,XXXXXXXX,XX______,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,_X____X_,________,
  _X______,X______X,________,
  __X____X,XXXXXXXX,X_______,
  _______X,________,________,
  ____X___,X_____X_,________,
  ____X___,X__X__X_,________,
  ___X____,X__X__X_,________,
  ___X____,X__X__X_,________,
  __X_____,X__X__X_,________,
  __X_____,X__X__X_,__X_____,
  _X_____X,___X__X_,__X_____,
  _X____X_,___X___X,XX______,
  _____X__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_70B9[ 57] = { /* code 70B9 */
  ________,X_______,________,
  ________,X_______,________,
  ________,XXXXXXXX,X_______,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ___XXXXX,XXXXXXX_,________,
  ___X____,______X_,________,
  ___X____,______X_,________,
  ___X____,______X_,________,
  ___X____,______X_,________,
  ___XXXXX,XXXXXXX_,________,
  ________,________,________,
  ________,________,________,
  ___X__X_,__X____X,________,
  __X___X_,___X____,X_______,
  __X____X,___X____,_X______,
  _X_____X,____X___,_X______,
  XX______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_7535[ 38] = { /* code 7535 */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  XXXXXXXX,XXXXX___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  XXXXXXXX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,_______X,
  ______X_,______X_,
  ______XX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_7F6E[ 51] = { /* code 7F6E */
  __XXXXXX,XXXXXXXX,________,
  __X___X_,___X____,X_______,
  __X___X_,___X____,X_______,
  __XXXXXX,XXXXXXXX,________,
  ________,X_______,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,XX______,
  ________,X_______,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,______X_,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,______X_,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,______X_,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,______X_,________,
  XXXXXXXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_8003[ 57] = { /* code 8003 */
  ________,X_______,________,
  ________,X_____X_,________,
  ________,X_____X_,________,
  ___XXXXX,XXXX_X__,________,
  ________,X___X___,________,
  ________,X__X____,________,
  XXXXXXXX,XXXXXXXX,XXX_____,
  ________,__X_____,________,
  ________,_X______,________,
  _______X,XXXXXXXX,X_______,
  ______X_,_X______,________,
  _____X__,_X______,________,
  ____X___,_X______,________,
  __XX____,XXXXXXXX,________,
  XX______,_______X,________,
  ________,______X_,________,
  ________,______X_,________,
  ________,______X_,________,
  ________,__XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_8BBE[ 57] = { /* code 8BBE */
  __X_____,_XXXXXX_,________,
  ___X____,_X____X_,________,
  ____X___,_X____X_,________,
  ________,_X____X_,________,
  ________,X_____X_,________,
  ________,X_____X_,__X_____,
  XXXX___X,_______X,XX______,
  ___X____,________,________,
  ___X____,________,________,
  ___X___X,XXXXXXXX,________,
  ___X____,_X_____X,________,
  ___X____,_X____X_,________,
  ___X__X_,__X___X_,________,
  ___X_X__,__X__X__,________,
  ___X_X__,___X_X__,________,
  ___XX___,___XX___,________,
  ___X____,__X__XX_,________,
  ________,XX_____X,XXX_____,
  ______XX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_8FD4[ 54] = { /* code 8FD4 */
  _X______,______XX,X_______,
  __XX___X,XXXXXX__,________,
  ___XX__X,________,________,
  ____X__X,________,________,
  _______X,________,________,
  ________,XXXXXXXX,________,
  ________,X______X,________,
  XXXX___X,______X_,________,
  ___X___X,__X___X_,________,
  ___X___X,___X__X_,________,
  ___X___X,____XX__,________,
  ___X___X,____X_X_,________,
  ___X__X_,___XX__X,________,
  ___X__X_,__X_____,X_______,
  ___X_X__,XX______,________,
  __XXX___,________,________,
  _X___XX_,________,________,
  X______X,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_9009[ 54] = { /* code 9009 */
  ________,___X____,________,
  ________,X__X____,________,
  _XX_____,X__X____,________,
  ___X___X,XXXXXXXX,X_______,
  _______X,___X____,________,
  ______X_,___X____,________,
  ________,___X____,________,
  XXXX_XXX,XXXXXXXX,XX______,
  ___X____,_X___X__,________,
  ___X____,_X___X__,________,
  ___X____,_X___X__,________,
  ___X____,_X___X__,________,
  ___X____,_X___X__,_X______,
  ___X____,X____X__,_X______,
  ___X__XX,_____XXX,X_______,
  __XXX_X_,________,________,
  _XX__XX_,________,________,
  X______X,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_96F6[ 54] = { /* code 96F6 */
  __XXXXXX,XXXXXXXX,X_______,
  ________,_X______,________,
  _XXXXXXX,XXXXXXXX,XX______,
  _X______,_X______,_X______,
  _X_XXXXX,_X_XXXXX,_X______,
  _X______,_X______,_X______,
  ___XXXXX,_X_XXXXX,________,
  ________,XX______,________,
  ______XX,__XX____,________,
  _____X__,X___XX__,________,
  ___XX___,_X____XX,X_______,
  XXX_____,__X_____,_XX_____,
  ___XXXXX,XXXXXXX_,________,
  ________,_____X__,________,
  ________,___XX___,________,
  ______XX,XXX_____,________,
  ________,_XX_____,________,
  ________,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_22_987A[ 57] = { /* code 987A */
  __X____X,_XXXXXXX,XXX_____,
  __X_X__X,_____X__,________,
  __X_X__X,_____X__,________,
  __X_X__X,____X___,________,
  __X_X__X,__XXXXXX,XX______,
  __X_X__X,__X_____,_X______,
  __X_X__X,__X_____,_X______,
  __X_X__X,__X__XX_,_X______,
  __X_X__X,__X__X__,_X______,
  __X_X__X,__X__X__,_X______,
  __X_X__X,__X__X__,_X______,
  _X__X__X,__X__X__,_X______,
  _X__X__X,__X__X__,_X______,
  _X__X__X,__X__X__,_X______,
  _X__X__X,_____X_X,________,
  _X__X__X,____X___,X_______,
  X______X,___X____,_X______,
  X______X,_XX_____,__X_____,
  ________,XX______,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDengXian_22_CharInfo[50] = {
   {   1,   1,   0,  17,   6, acGUI_FontDengXian_22_0020 } /* code 0020, SPACE */
  ,{  10,  10,   2,   6,  14, acGUI_FontDengXian_22_002B } /* code 002B, PLUS SIGN */
  ,{   6,   1,   2,  12,  11, acGUI_FontDengXian_22_002D } /* code 002D, HYPHEN-MINUS */
  ,{   1,   1,   2,  17,   5, acGUI_FontDengXian_22_002E } /* code 002E, FULL STOP */
  ,{   9,  15,   1,   3,  11, acGUI_FontDengXian_22_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  15,   1,   3,  11, acGUI_FontDengXian_22_0031 } /* code 0031, DIGIT ONE */
  ,{   8,  15,   1,   3,  11, acGUI_FontDengXian_22_0032 } /* code 0032, DIGIT TWO */
  ,{   9,  15,   1,   3,  11, acGUI_FontDengXian_22_0033 } /* code 0033, DIGIT THREE */
  ,{   9,  15,   1,   3,  11, acGUI_FontDengXian_22_0034 } /* code 0034, DIGIT FOUR */
  ,{   9,  15,   1,   3,  11, acGUI_FontDengXian_22_0035 } /* code 0035, DIGIT FIVE */
  ,{   9,  15,   1,   3,  11, acGUI_FontDengXian_22_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  15,   1,   3,  11, acGUI_FontDengXian_22_0037 } /* code 0037, DIGIT SEVEN */
  ,{   9,  15,   1,   3,  11, acGUI_FontDengXian_22_0038 } /* code 0038, DIGIT EIGHT */
  ,{   9,  15,   1,   3,  11, acGUI_FontDengXian_22_0039 } /* code 0039, DIGIT NINE */
  ,{  10,  10,   2,   6,  14, acGUI_FontDengXian_22_003E } /* code 003E, GREATER-THAN SIGN */
  ,{  13,  15,   0,   3,  13, acGUI_FontDengXian_22_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   9,  15,   2,   3,  11, acGUI_FontDengXian_22_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  11,  15,   1,   3,  13, acGUI_FontDengXian_22_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  11,  15,   2,   3,  14, acGUI_FontDengXian_22_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   8,  15,   2,   3,  11, acGUI_FontDengXian_22_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   7,  15,   2,   3,  10, acGUI_FontDengXian_22_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  11,  15,   2,   3,  15, acGUI_FontDengXian_22_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  14,  19,   1,   3,  16, acGUI_FontDengXian_22_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   8,  15,   1,   3,  10, acGUI_FontDengXian_22_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  10,  15,   2,   3,  14, acGUI_FontDengXian_22_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  12,  15,   0,   3,  13, acGUI_FontDengXian_22_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{   9,   1,   0,  20,   9, acGUI_FontDengXian_22_005F } /* code 005F, LOW LINE */
  ,{   8,  11,   2,   7,  11, acGUI_FontDengXian_22_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   9,   9,   2,   6,  14, acGUI_FontDengXian_22_00D7 } /* code 00D7, MULTIPLICATION SIGN */
  ,{  15,  19,   3,   1,  21, acGUI_FontDengXian_22_4E2D } /* code 4E2D */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_51C6 } /* code 51C6 */
  ,{  18,  20,   1,   0,  21, acGUI_FontDengXian_22_52A8 } /* code 52A8 */
  ,{  21,  20,   0,   0,  21, acGUI_FontDengXian_22_53C2 } /* code 53C2 */
  ,{  15,  17,   3,   3,  21, acGUI_FontDengXian_22_56DE } /* code 56DE */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_5E8F } /* code 5E8F */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_5F0F } /* code 5F0F */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_624B } /* code 624B */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_62E9 } /* code 62E9 */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_6821 } /* code 6821 */
  ,{  20,  19,   0,   1,  21, acGUI_FontDengXian_22_6A21 } /* code 6A21 */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_6D41 } /* code 6D41 */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_70B9 } /* code 70B9 */
  ,{  16,  19,   4,   1,  21, acGUI_FontDengXian_22_7535 } /* code 7535 */
  ,{  19,  17,   1,   2,  21, acGUI_FontDengXian_22_7F6E } /* code 7F6E */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_8003 } /* code 8003 */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_8BBE } /* code 8BBE */
  ,{  19,  18,   1,   1,  21, acGUI_FontDengXian_22_8FD4 } /* code 8FD4 */
  ,{  19,  18,   1,   1,  21, acGUI_FontDengXian_22_9009 } /* code 9009 */
  ,{  19,  18,   1,   2,  21, acGUI_FontDengXian_22_96F6 } /* code 96F6 */
  ,{  19,  19,   1,   1,  21, acGUI_FontDengXian_22_987A } /* code 987A */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop35 = {
   0x987A /* first character */
  ,0x987A /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 49] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop34 = {
   0x96F6 /* first character */
  ,0x96F6 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 48] /* address of first character */
  ,&GUI_FontDengXian_22_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop33 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 47] /* address of first character */
  ,&GUI_FontDengXian_22_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop32 = {
   0x8FD4 /* first character */
  ,0x8FD4 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 46] /* address of first character */
  ,&GUI_FontDengXian_22_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop31 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 45] /* address of first character */
  ,&GUI_FontDengXian_22_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop30 = {
   0x8003 /* first character */
  ,0x8003 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 44] /* address of first character */
  ,&GUI_FontDengXian_22_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop29 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 43] /* address of first character */
  ,&GUI_FontDengXian_22_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop28 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 42] /* address of first character */
  ,&GUI_FontDengXian_22_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop27 = {
   0x70B9 /* first character */
  ,0x70B9 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 41] /* address of first character */
  ,&GUI_FontDengXian_22_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop26 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 40] /* address of first character */
  ,&GUI_FontDengXian_22_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop25 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 39] /* address of first character */
  ,&GUI_FontDengXian_22_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop24 = {
   0x6821 /* first character */
  ,0x6821 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 38] /* address of first character */
  ,&GUI_FontDengXian_22_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop23 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 37] /* address of first character */
  ,&GUI_FontDengXian_22_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop22 = {
   0x624B /* first character */
  ,0x624B /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 36] /* address of first character */
  ,&GUI_FontDengXian_22_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop21 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 35] /* address of first character */
  ,&GUI_FontDengXian_22_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop20 = {
   0x5E8F /* first character */
  ,0x5E8F /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 34] /* address of first character */
  ,&GUI_FontDengXian_22_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop19 = {
   0x56DE /* first character */
  ,0x56DE /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 33] /* address of first character */
  ,&GUI_FontDengXian_22_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop18 = {
   0x53C2 /* first character */
  ,0x53C2 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 32] /* address of first character */
  ,&GUI_FontDengXian_22_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop17 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 31] /* address of first character */
  ,&GUI_FontDengXian_22_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop16 = {
   0x51C6 /* first character */
  ,0x51C6 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 30] /* address of first character */
  ,&GUI_FontDengXian_22_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop15 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 29] /* address of first character */
  ,&GUI_FontDengXian_22_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop14 = {
   0x00D7 /* first character */
  ,0x00D7 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 28] /* address of first character */
  ,&GUI_FontDengXian_22_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop13 = {
   0x0075 /* first character */
  ,0x0075 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 27] /* address of first character */
  ,&GUI_FontDengXian_22_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop12 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 26] /* address of first character */
  ,&GUI_FontDengXian_22_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop11 = {
   0x0055 /* first character */
  ,0x0056 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 24] /* address of first character */
  ,&GUI_FontDengXian_22_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop10 = {
   0x0053 /* first character */
  ,0x0053 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 23] /* address of first character */
  ,&GUI_FontDengXian_22_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop9 = {
   0x0051 /* first character */
  ,0x0051 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 22] /* address of first character */
  ,&GUI_FontDengXian_22_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop8 = {
   0x004E /* first character */
  ,0x004E /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 21] /* address of first character */
  ,&GUI_FontDengXian_22_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop7 = {
   0x004C /* first character */
  ,0x004C /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 20] /* address of first character */
  ,&GUI_FontDengXian_22_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop6 = {
   0x0041 /* first character */
  ,0x0045 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 15] /* address of first character */
  ,&GUI_FontDengXian_22_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop5 = {
   0x003E /* first character */
  ,0x003E /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[ 14] /* address of first character */
  ,&GUI_FontDengXian_22_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop4 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[  4] /* address of first character */
  ,&GUI_FontDengXian_22_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop3 = {
   0x002D /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[  2] /* address of first character */
  ,&GUI_FontDengXian_22_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop2 = {
   0x002B /* first character */
  ,0x002B /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[  1] /* address of first character */
  ,&GUI_FontDengXian_22_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_22_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontDengXian_22_CharInfo[  0] /* address of first character */
  ,&GUI_FontDengXian_22_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDengXian_22 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,&GUI_FontDengXian_22_Prop1
  ,17 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

