/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DengXian_48.c                                         *
* Font:        µ»œﬂ                                                  *
* Height:      48                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  48                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x56 (86)                                     *
* Character enabled:   0x3BC (956)                                   *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDengXian_48;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_48_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_48_0041[128] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,____XXXX,________,________,
  ________,____XXXX,________,________,
  ________,___XXXXX,X_______,________,
  ________,___XXXXX,X_______,________,
  ________,___XX__X,XX______,________,
  ________,__XXX__X,XX______,________,
  ________,__XXX__X,XX______,________,
  ________,_XXX____,XXX_____,________,
  ________,_XXX____,XXX_____,________,
  ________,_XXX____,XXX_____,________,
  ________,XXX_____,_XXX____,________,
  ________,XXX_____,_XXX____,________,
  _______X,XX______,__XXX___,________,
  _______X,XX______,__XXX___,________,
  _______X,XX______,__XXX___,________,
  ______XX,X_______,___XXX__,________,
  ______XX,X_______,___XXX__,________,
  ______XX,________,____XX__,________,
  _____XXX,________,____XXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXX_,________,_____XXX,________,
  ___XXX__,________,______XX,X_______,
  ___XXX__,________,______XX,X_______,
  __XXXX__,________,______XX,XX______,
  __XXX___,________,_______X,XX______,
  __XXX___,________,_______X,XX______,
  _XXX____,________,________,XXX_____,
  _XXX____,________,________,XXX_____,
  _XXX____,________,________,XXX_____,
  XXX_____,________,________,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_48_0056[128] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXX____,________,________,XXXX____,
  _XXX____,________,________,XXX_____,
  _XXX____,________,________,XXX_____,
  _XXXX___,________,_______X,XXX_____,
  __XXX___,________,_______X,XX______,
  __XXX___,________,_______X,XX______,
  __XXXX__,________,______XX,XX______,
  ___XXX__,________,______XX,X_______,
  ___XXX__,________,______XX,X_______,
  ____XXX_,________,_____XXX,________,
  ____XXX_,________,_____XXX,________,
  ____XXXX,________,____XXXX,________,
  _____XXX,________,____XXX_,________,
  _____XXX,________,____XXX_,________,
  ______XX,X_______,___XXX__,________,
  ______XX,X_______,___XXX__,________,
  ______XX,X_______,___XXX__,________,
  _______X,XX______,__XXX___,________,
  _______X,XX______,__XXX___,________,
  _______X,XXX_____,_XXXX___,________,
  ________,XXX_____,_XXX____,________,
  ________,XXX_____,_XXX____,________,
  ________,_XXX____,XXX_____,________,
  ________,_XXX____,XXX_____,________,
  ________,_XXX____,XXX_____,________,
  ________,__XXX__X,XX______,________,
  ________,__XXX__X,XX______,________,
  ________,___XX__X,XX______,________,
  ________,___XXXXX,X_______,________,
  ________,___XXXXX,X_______,________,
  ________,____XXXX,________,________,
  ________,____XXXX,________,________};

/* Start of unicode area <Basic Greek> */
GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_48_03BC[ 96] = { /* code 03BC, GREEK SMALL LETTER MU */
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,_____XXX,XX______,
  XXXXX___,____XX_X,XX______,
  XXXXXX__,___XX__X,XXX_____,
  XXX_XXXX,XXXX____,XXXXX___,
  XXX___XX,XXX_____,_XXXX___,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDengXian_48_CharInfo[4] = {
   {   1,   1,   0,  37,  13, acGUI_FontDengXian_48_0020 } /* code 0020, SPACE */
  ,{  28,  32,   1,   7,  29, acGUI_FontDengXian_48_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  28,  32,   0,   7,  28, acGUI_FontDengXian_48_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  21,  32,   4,  16,  26, acGUI_FontDengXian_48_03BC } /* code 03BC, GREEK SMALL LETTER MU */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_48_Prop4 = {
   0x03BC /* first character */
  ,0x03BC /* last character  */
  ,&GUI_FontDengXian_48_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_48_Prop3 = {
   0x0056 /* first character */
  ,0x0056 /* last character  */
  ,&GUI_FontDengXian_48_CharInfo[  2] /* address of first character */
  ,&GUI_FontDengXian_48_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_48_Prop2 = {
   0x0041 /* first character */
  ,0x0041 /* last character  */
  ,&GUI_FontDengXian_48_CharInfo[  1] /* address of first character */
  ,&GUI_FontDengXian_48_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_48_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontDengXian_48_CharInfo[  0] /* address of first character */
  ,&GUI_FontDengXian_48_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDengXian_48 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,48 /* height of font  */
  ,48 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,&GUI_FontDengXian_48_Prop1
  ,37 /* Baseline */
  ,23 /* Height of lowercase characters */
  ,32 /* Height of capital characters */
};

