/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DengXian_14.c                                         *
* Font:        Adobe ���� Std L                                      *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDengXian_14;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0025[ 24] = { /* code 0025, PERCENT SIGN */
  __X_____,_XX_____,
  _X_X____,_X______,
  X___X___,X_______,
  X___X___,X_______,
  X___X__X,________,
  X___X_X_,__X_____,
  _X_X__X_,_X_X____,
  __X__X__,X___X___,
  ____X___,X___X___,
  ____X___,X___X___,
  ___X____,X___X___,
  __X_____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_002E[  2] = { /* code 002E, FULL STOP */
  X_______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0030[ 12] = { /* code 0030, DIGIT ZERO */
  __XXX___,
  _X___X__,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0031[ 12] = { /* code 0031, DIGIT ONE */
  __X_____,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0032[ 12] = { /* code 0032, DIGIT TWO */
  ___XX___,
  _XX__X__,
  _X____X_,
  ______X_,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X_____X,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0033[ 12] = { /* code 0033, DIGIT THREE */
  __XXX___,
  _X___X__,
  _____X__,
  _____X__,
  ___XX___,
  _XX__X__,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  XX__XX__,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0034[ 12] = { /* code 0034, DIGIT FOUR */
  _____X__,
  _____X__,
  ____XX__,
  ___X_X__,
  ___X_X__,
  __X__X__,
  _X___X__,
  _X___X__,
  XXXXXXXX,
  _____X__,
  _____X__,
  ___XXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0035[ 12] = { /* code 0035, DIGIT FIVE */
  __XXXXX_,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  _____X__,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  XX__XX__,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0036[ 12] = { /* code 0036, DIGIT SIX */
  _____XX_,
  ___XX___,
  __X_____,
  _X______,
  _X______,
  X_XXX___,
  XX___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0037[ 12] = { /* code 0037, DIGIT SEVEN */
  _XXXXXX_,
  X______X,
  ______X_,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0038[ 12] = { /* code 0038, DIGIT EIGHT */
  __XX____,
  _X__X___,
  X____X__,
  X____X__,
  _X__X___,
  __XX____,
  _X__XX__,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0039[ 12] = { /* code 0039, DIGIT NINE */
  __XXX___,
  _X___X__,
  X____X__,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___XX_,
  __XXX_X_,
  _____X__,
  ____XX__,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_003A[  8] = { /* code 003A, COLON */
  XX______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0046[ 24] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,________,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,________,
  __X____X,________,
  __XXXXXX,________,
  __X____X,________,
  __X____X,________,
  __X_____,________,
  __X_____,________,
  __X_____,________,
  XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0050[ 12] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  __X___X_,
  __X____X,
  __X____X,
  __X____X,
  __X___X_,
  __XXXX__,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_14_0057[ 36] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXX____,_X____XX,XX______,
  __X_____,_X_____X,________,
  __X_____,XX_____X,________,
  __X_____,XX_____X,________,
  ___X___X,__X___X_,________,
  ___X___X,__X___X_,________,
  ___X___X,__X___X_,________,
  ____X_X_,___X_X__,________,
  ____X_X_,___X_X__,________,
  ____XX__,___X_X__,________,
  _____X__,____X___,________,
  _____X__,____X___,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDengXian_14_CharInfo[16] = {
   {  13,  12,   1,   5,  15, acGUI_FontDengXian_14_0025 } /* code 0025, PERCENT SIGN */
  ,{   2,   2,   1,  15,   5, acGUI_FontDengXian_14_002E } /* code 002E, FULL STOP */
  ,{   7,  12,   1,   5,   9, acGUI_FontDengXian_14_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  12,   2,   5,   9, acGUI_FontDengXian_14_0031 } /* code 0031, DIGIT ONE */
  ,{   8,  12,   0,   5,   9, acGUI_FontDengXian_14_0032 } /* code 0032, DIGIT TWO */
  ,{   7,  12,   1,   5,   9, acGUI_FontDengXian_14_0033 } /* code 0033, DIGIT THREE */
  ,{   8,  12,   0,   5,   9, acGUI_FontDengXian_14_0034 } /* code 0034, DIGIT FOUR */
  ,{   7,  12,   1,   5,   9, acGUI_FontDengXian_14_0035 } /* code 0035, DIGIT FIVE */
  ,{   7,  12,   1,   5,   9, acGUI_FontDengXian_14_0036 } /* code 0036, DIGIT SIX */
  ,{   8,  12,   1,   5,   9, acGUI_FontDengXian_14_0037 } /* code 0037, DIGIT SEVEN */
  ,{   7,  12,   1,   5,   9, acGUI_FontDengXian_14_0038 } /* code 0038, DIGIT EIGHT */
  ,{   7,  12,   1,   5,   9, acGUI_FontDengXian_14_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   8,   1,   9,   5, acGUI_FontDengXian_14_003A } /* code 003A, COLON */
  ,{   9,  12,   1,   5,  10, acGUI_FontDengXian_14_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   8,  12,   1,   5,  10, acGUI_FontDengXian_14_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  18,  12,   0,   5,  18, acGUI_FontDengXian_14_0057 } /* code 0057, LATIN CAPITAL LETTER W */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_14_Prop6 = {
   0x0057 /* first character */
  ,0x0057 /* last character  */
  ,&GUI_FontDengXian_14_CharInfo[ 15] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_14_Prop5 = {
   0x0050 /* first character */
  ,0x0050 /* last character  */
  ,&GUI_FontDengXian_14_CharInfo[ 14] /* address of first character */
  ,&GUI_FontDengXian_14_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_14_Prop4 = {
   0x0046 /* first character */
  ,0x0046 /* last character  */
  ,&GUI_FontDengXian_14_CharInfo[ 13] /* address of first character */
  ,&GUI_FontDengXian_14_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_14_Prop3 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontDengXian_14_CharInfo[  2] /* address of first character */
  ,&GUI_FontDengXian_14_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_14_Prop2 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontDengXian_14_CharInfo[  1] /* address of first character */
  ,&GUI_FontDengXian_14_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_14_Prop1 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontDengXian_14_CharInfo[  0] /* address of first character */
  ,&GUI_FontDengXian_14_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDengXian_14 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontDengXian_14_Prop1}
  ,17 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

