/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DengXian_32.c                                         *
* Font:        µ»œﬂ                                                  *
* Height:      32                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  32                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x39 (57)                                     *
* Character enabled:   0x2E (46)                                     *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x56 (86)                                     *
* Character enabled:   0x3BC (956)                                   *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDengXian_32;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_002E[  3] = { /* code 002E, FULL STOP */
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0030[ 42] = { /* code 0030, DIGIT ZERO */
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  __XXX___,_XXX____,
  _XXX____,__XXX___,
  _XX_____,___XX___,
  _XX_____,___XX___,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  _XX_____,___XX___,
  _XX_____,___XX___,
  _XXX____,__XXX___,
  __XXX___,_XXX____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0031[ 42] = { /* code 0031, DIGIT ONE */
  _____XX_,________,
  ___XXXX_,________,
  __XX_XX_,________,
  _XX__XX_,________,
  _X___XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0032[ 42] = { /* code 0032, DIGIT TWO */
  ___XXXXX,X_______,
  __XXXXXX,XXX_____,
  _XXX____,XXX_____,
  XX______,_XXX____,
  XX______,__XX____,
  ________,__XX____,
  ________,__XX____,
  ________,__XX____,
  ________,_XX_____,
  ________,_XX_____,
  ________,XX______,
  _______X,X_______,
  ______XX,________,
  _____XX_,________,
  ____XX__,________,
  ___XX___,________,
  __XX____,________,
  _XX_____,________,
  _X______,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0033[ 42] = { /* code 0033, DIGIT THREE */
  ___XXXXX,XX______,
  __XXXXXX,XXX_____,
  _XXX____,_XXX____,
  XXX_____,__XXX___,
  XX______,___XX___,
  ________,___XX___,
  ________,___XX___,
  ________,__XX____,
  ________,_XXX____,
  _____XXX,XX______,
  _____XXX,XXX_____,
  ________,__XXX___,
  ________,___XX___,
  ________,____XX__,
  ________,____XX__,
  ________,____XX__,
  XX______,____XX__,
  XXX_____,___XXX__,
  _XXX____,__XXX___,
  __XXXXXX,XXXX____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0034[ 42] = { /* code 0034, DIGIT FOUR */
  ________,_XX_____,
  ________,XXX_____,
  _______X,XXX_____,
  _______X,_XX_____,
  ______XX,_XX_____,
  ______X_,_XX_____,
  _____XX_,_XX_____,
  ____XX__,_XX_____,
  ____X___,_XX_____,
  ___XX___,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  _XX_____,_XX_____,
  _X______,_XX_____,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0035[ 42] = { /* code 0035, DIGIT FIVE */
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __X_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_XXXX,XX______,
  _XXXXXXX,XXXX____,
  _XXX____,__XXX___,
  ________,___XXX__,
  ________,____XX__,
  ________,____XX__,
  ________,____XX__,
  ________,____XX__,
  XX______,____XX__,
  XXX_____,___XX___,
  _XXX____,__XXX___,
  __XXXXXX,XXXX____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0036[ 42] = { /* code 0036, DIGIT SIX */
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  __XXX___,_XXX____,
  _XXX____,__XX____,
  _XX_____,________,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX__XXXX,XX______,
  XXXXXXXX,XXX_____,
  XXXX____,_XXX____,
  XXX_____,__XXX___,
  XX______,___XX___,
  XX______,___XX___,
  XX______,___XX___,
  XX______,___XX___,
  _XX_____,___XX___,
  _XX_____,__XX____,
  __XX____,_XXX____,
  ___XXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0037[ 42] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  ________,___X____,
  ________,__XX____,
  ________,_XX_____,
  ________,_XX_____,
  ________,XX______,
  ________,XX______,
  _______X,X_______,
  _______X,X_______,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0038[ 42] = { /* code 0038, DIGIT EIGHT */
  ___XXXXX,XX______,
  __XXXXXX,XXX_____,
  _XXX____,_XXX____,
  XXX_____,__XXX___,
  XX______,___XX___,
  XX______,___XX___,
  XX______,___XX___,
  _XX_____,__XX____,
  _XXX____,_XXX____,
  ___XXXXX,XX______,
  ___XXXXX,XX______,
  _XXX____,_XXX____,
  _XX_____,__XX____,
  XX______,___XX___,
  XX______,___XX___,
  XX______,___XX___,
  XX______,___XX___,
  XXX_____,__XXX___,
  _XXX____,_XXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0039[ 42] = { /* code 0039, DIGIT NINE */
  ____XXXX,X_______,
  __XXXXXX,XX______,
  _XXX____,_XX_____,
  _XX_____,__XX____,
  XX______,__XX____,
  XX______,___XX___,
  XX______,___XX___,
  XX______,___XX___,
  XX______,___XX___,
  XX______,___XX___,
  _XX_____,__XXX___,
  _XXX____,_XXXX___,
  __XXXXXX,XX_XX___,
  ___XXXXX,___XX___,
  ________,___XX___,
  ________,__XX____,
  ________,__XX____,
  XX______,_XXX____,
  _XX_____,XXX_____,
  _XXXXXXX,XX______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0041[ 63] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,XXX_____,________,
  ________,XXX_____,________,
  _______X,X_XX____,________,
  _______X,X_XX____,________,
  _______X,X_XX____,________,
  ______XX,___XX___,________,
  ______XX,___XX___,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,________,
  ___XX___,______XX,________,
  ___XXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,________,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  _XXX____,_______X,XX______,
  _XX_____,________,XX______,
  _XX_____,________,XX______,
  XX______,________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_0056[ 63] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX______,________,_XX_____,
  _XX_____,________,XX______,
  _XX_____,________,XX______,
  _XXX____,_______X,XX______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  ___XX___,______XX,________,
  ___XX___,______XX,________,
  ___XXX__,_____XXX,________,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  ______XX,___XX___,________,
  ______XX,___XX___,________,
  _______X,X_XX____,________,
  _______X,X_XX____,________,
  _______X,X_XX____,________,
  ________,XXX_____,________,
  ________,XXX_____,________};

/* Start of unicode area <Basic Greek> */
GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_32_03BC[ 42] = { /* code 03BC, GREEK SMALL LETTER MU */
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,_XXX____,
  XXX_____,_XXX____,
  XXXX____,XXXX____,
  XXXXXXXX,X_XXXX__,
  XX_XXXXX,___XXX__,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDengXian_32_CharInfo[14] = {
   {   2,   3,   2,  23,   7, acGUI_FontDengXian_32_002E } /* code 002E, FULL STOP */
  ,{  14,  21,   1,   5,  16, acGUI_FontDengXian_32_0030 } /* code 0030, DIGIT ZERO */
  ,{  12,  21,   2,   5,  16, acGUI_FontDengXian_32_0031 } /* code 0031, DIGIT ONE */
  ,{  12,  21,   2,   5,  16, acGUI_FontDengXian_32_0032 } /* code 0032, DIGIT TWO */
  ,{  14,  21,   1,   5,  16, acGUI_FontDengXian_32_0033 } /* code 0033, DIGIT THREE */
  ,{  14,  21,   1,   5,  16, acGUI_FontDengXian_32_0034 } /* code 0034, DIGIT FOUR */
  ,{  14,  21,   1,   5,  16, acGUI_FontDengXian_32_0035 } /* code 0035, DIGIT FIVE */
  ,{  13,  21,   2,   5,  16, acGUI_FontDengXian_32_0036 } /* code 0036, DIGIT SIX */
  ,{  13,  21,   2,   5,  16, acGUI_FontDengXian_32_0037 } /* code 0037, DIGIT SEVEN */
  ,{  13,  21,   2,   5,  16, acGUI_FontDengXian_32_0038 } /* code 0038, DIGIT EIGHT */
  ,{  13,  21,   2,   5,  16, acGUI_FontDengXian_32_0039 } /* code 0039, DIGIT NINE */
  ,{  19,  21,   0,   5,  20, acGUI_FontDengXian_32_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  19,  21,   0,   5,  19, acGUI_FontDengXian_32_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  14,  21,   3,  11,  17, acGUI_FontDengXian_32_03BC } /* code 03BC, GREEK SMALL LETTER MU */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_32_Prop5 = {
   0x03BC /* first character */
  ,0x03BC /* last character  */
  ,&GUI_FontDengXian_32_CharInfo[ 13] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_32_Prop4 = {
   0x0056 /* first character */
  ,0x0056 /* last character  */
  ,&GUI_FontDengXian_32_CharInfo[ 12] /* address of first character */
  ,&GUI_FontDengXian_32_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_32_Prop3 = {
   0x0041 /* first character */
  ,0x0041 /* last character  */
  ,&GUI_FontDengXian_32_CharInfo[ 11] /* address of first character */
  ,&GUI_FontDengXian_32_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_32_Prop2 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontDengXian_32_CharInfo[  1] /* address of first character */
  ,&GUI_FontDengXian_32_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_32_Prop1 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontDengXian_32_CharInfo[  0] /* address of first character */
  ,&GUI_FontDengXian_32_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDengXian_32 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,32 /* height of font  */
  ,32 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,&GUI_FontDengXian_32_Prop1
  ,25 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,21 /* Height of capital characters */
};

