/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DengXian_24.c                                         *
* Font:        <unknown>                                             *
* Height:      36                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  36                                           *
* Character disabled:  0x30 (48)                                     *
* Character disabled:  0x31 (49)                                     *
* Character disabled:  0x32 (50)                                     *
* Character disabled:  0x33 (51)                                     *
* Character disabled:  0x34 (52)                                     *
* Character disabled:  0x35 (53)                                     *
* Character disabled:  0x36 (54)                                     *
* Character disabled:  0x37 (55)                                     *
* Character disabled:  0x38 (56)                                     *
* Character disabled:  0x39 (57)                                     *
* Character disabled:  0x28 (40)                                     *
* Character disabled:  0x29 (41)                                     *
* Character disabled:  0x2E (46)                                     *
* Character disabled:  0x41 (65)                                     *
* Character disabled:  0x44 (68)                                     *
* Character disabled:  0x43 (67)                                     *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x43 (67)                                     *
* Character disabled:  0x43 (67)                                     *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x39 (57)                                     *
* Character enabled:   0x29 (41)                                     *
* Character enabled:   0x28 (40)                                     *
* Character enabled:   0x2E (46)                                     *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x42 (66)                                     *
* Character enabled:   0x43 (67)                                     *
* Character disabled:  0x42 (66)                                     *
* Character enabled:   0x44 (68)                                     *
* Character enabled:   0x56 (86)                                     *
* Character enabled:   0x50 (80)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDengXian_24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0028[ 29] = { /* code 0028, LEFT PARENTHESIS */
  ______XX,
  _____XX_,
  ____XX__,
  ___XXX__,
  ___XX___,
  __XXX___,
  __XX____,
  _XXX____,
  _XXX____,
  _XXX____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  _XXX____,
  _XXX____,
  _XXX____,
  __XXX___,
  __XXX___,
  ___XX___,
  ___XXX__,
  ____XX__,
  _____XX_,
  ______XX};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0029[ 29] = { /* code 0029, RIGHT PARENTHESIS */
  XX______,
  _XX_____,
  __XX____,
  __XXX___,
  ___XX___,
  ___XXX__,
  ____XX__,
  ____XXX_,
  ____XXX_,
  ____XXX_,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  ____XXX_,
  ____XXX_,
  ____XXX_,
  ___XXX__,
  ___XXX__,
  ___XX___,
  __XXX___,
  __XX____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_002E[  3] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0030[ 46] = { /* code 0030, DIGIT ZERO */
  _____XXX,XXX_____,
  ___XXXXX,XXXXX___,
  __XXXXXX,XXXXXX__,
  _XXXXX__,__XXXX__,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXXXX__,__XXXXX_,
  __XXXXXX,XXXXXX__,
  ___XXXXX,XXXXX___,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0031[ 46] = { /* code 0031, DIGIT ONE */
  _______X,X_______,
  ______XX,X_______,
  _____XXX,X_______,
  ____XXXX,X_______,
  __XXXXXX,X_______,
  _XXXX_XX,X_______,
  XXXX__XX,X_______,
  XX____XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0032[ 46] = { /* code 0032, DIGIT TWO */
  ____XXXX,XXX_____,
  __XXXXXX,XXXXX___,
  _XXXXXXX,XXXXXX__,
  _XXXX___,__XXXX__,
  XXX_____,___XXXX_,
  XXX_____,____XXX_,
  ________,____XXX_,
  ________,____XXX_,
  ________,____XXX_,
  ________,___XXX__,
  ________,___XXX__,
  ________,__XXX___,
  ________,_XXX____,
  ________,XXX_____,
  _______X,XX______,
  _____XXX,X_______,
  ____XXXX,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0033[ 46] = { /* code 0033, DIGIT THREE */
  _____XXX,XXX_____,
  ___XXXXX,XXXXX___,
  __XXXXXX,XXXXXX__,
  _XXXX___,__XXXX__,
  XXXX____,____XXX_,
  XXX_____,____XXX_,
  ________,____XXX_,
  ________,___XXXX_,
  ________,__XXXX__,
  ______XX,XXXXX___,
  ______XX,XXXXX___,
  ______XX,XXXXXX__,
  ________,___XXXX_,
  ________,____XXXX,
  ________,_____XXX,
  ________,_____XXX,
  ________,_____XXX,
  XXX_____,_____XXX,
  XXXX____,____XXX_,
  _XXXX___,___XXXX_,
  __XXXXXX,XXXXXX__,
  ___XXXXX,XXXXX___,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0034[ 46] = { /* code 0034, DIGIT FOUR */
  ________,___XX___,
  ________,__XXX___,
  ________,_XXXX___,
  ________,XXXXX___,
  ________,XXXXX___,
  _______X,XXXXX___,
  ______XX,X_XXX___,
  _____XXX,X_XXX___,
  _____XXX,__XXX___,
  ____XXX_,__XXX___,
  ___XXX__,__XXX___,
  ___XXX__,__XXX___,
  __XXX___,__XXX___,
  _XXX____,__XXX___,
  XXX_____,__XXX___,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0035[ 46] = { /* code 0035, DIGIT FIVE */
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX__XX,XXX_____,
  _XX_XXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  XXXXX___,___XXXX_,
  XXX_____,____XXX_,
  ________,_____XXX,
  ________,_____XXX,
  ________,_____XXX,
  ________,_____XXX,
  ________,_____XXX,
  XXX_____,_____XXX,
  XXXX____,____XXX_,
  _XXXX___,___XXXX_,
  _XXXXXXX,XXXXXX__,
  ___XXXXX,XXXXX___,
  ____XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0036[ 46] = { /* code 0036, DIGIT SIX */
  ______XX,XXXX____,
  ____XXXX,XXXXXX__,
  ___XXXXX,XXXXXXX_,
  __XXXX__,___XXXX_,
  _XXXX___,____XXXX,
  _XXX____,_____XXX,
  _XXX____,________,
  XXX_____,________,
  XXX___XX,XXXX____,
  XXX_XXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  XXXXXX__,___XXXX_,
  XXXX____,____XXXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  _XXX____,_____XXX,
  _XXX____,____XXX_,
  __XXXX__,___XXXX_,
  __XXXXXX,XXXXXX__,
  ____XXXX,XXXXX___,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0037[ 46] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ________,____XX__,
  ________,___XX___,
  ________,__XXX___,
  ________,_XXX____,
  ________,XXX_____,
  ________,XXX_____,
  _______X,XX______,
  _______X,XX______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0038[ 46] = { /* code 0038, DIGIT EIGHT */
  _____XXX,XXX_____,
  ___XXXXX,XXXXX___,
  __XXXXXX,XXXXXX__,
  _XXXX___,___XXX__,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  __XXX___,___XXX__,
  ___XXXXX,XXXXX___,
  ____XXXX,XXXX____,
  __XXXXXX,XXXXXX__,
  _XXXX___,___XXXX_,
  _XXX____,____XXX_,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXXX____,____XXXX,
  _XXXX___,___XXXX_,
  __XXXXXX,XXXXXX__,
  ___XXXXX,XXXXX___,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0039[ 46] = { /* code 0039, DIGIT NINE */
  _____XXX,XXX_____,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXXXX__,
  _XXXX___,___XXX__,
  _XXX____,____XXX_,
  XXX_____,_____XX_,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  XXXX____,____XXXX,
  _XXXX___,___XXXXX,
  __XXXXXX,XXXXXXXX,
  ___XXXXX,XXXX_XXX,
  ____XXXX,XX___XXX,
  ________,_____XXX,
  ________,____XXX_,
  XXX_____,____XXX_,
  XXXX____,___XXXX_,
  _XXXX___,__XXXX__,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXX____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0041[ 69] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,XXXXX___,________,
  ________,XXXXX___,________,
  ________,XXXXX___,________,
  _______X,XX_XXX__,________,
  _______X,XX_XXX__,________,
  _______X,XX_XXX__,________,
  ______XX,X___XXX_,________,
  ______XX,X___XXX_,________,
  _____XXX,_____XXX,________,
  _____XXX,_____XXX,________,
  _____XXX,_____XXX,________,
  ____XXX_,______XX,X_______,
  ____XXX_,______XX,X_______,
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XX______,
  __XXX___,________,XXX_____,
  __XXX___,________,XXX_____,
  __XXX___,________,XXX_____,
  _XXX____,________,_XXX____,
  _XXX____,________,_XXX____,
  _XXX____,________,_XXX____,
  XXX_____,________,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0043[ 69] = { /* code 0043, LATIN CAPITAL LETTER C */
  _______X,XXXXXX__,________,
  _____XXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XX______,
  ___XXXXX,______XX,XX______,
  __XXXX__,_______X,XXX_____,
  _XXXX___,________,XXXX____,
  _XXX____,________,_XXX____,
  XXXX____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  _XXX____,________,__XXX___,
  _XXX____,________,_XXXX___,
  _XXXX___,________,_XXX____,
  __XXXX__,________,XXXX____,
  ___XXXXX,______XX,XXX_____,
  ____XXXX,XXXXXXXX,XX______,
  _____XXX,XXXXXXXX,X_______,
  _______X,XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0044[ 69] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,________,
  XXX_____,____XXXX,X_______,
  XXX_____,______XX,X_______,
  XXX_____,______XX,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XXX_____,
  XXX_____,________,XXX_____,
  XXX_____,________,XXX_____,
  XXX_____,________,XXX_____,
  XXX_____,________,XXX_____,
  XXX_____,________,XXX_____,
  XXX_____,________,XXX_____,
  XXX_____,________,XXX_____,
  XXX_____,_______X,XXX_____,
  XXX_____,_______X,XX______,
  XXX_____,______XX,XX______,
  XXX_____,______XX,X_______,
  XXX_____,____XXXX,X_______,
  XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0050[ 69] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,________,
  XXX_____,____XXXX,________,
  XXX_____,_____XXX,X_______,
  XXX_____,______XX,X_______,
  XXX_____,______XX,X_______,
  XXX_____,______XX,X_______,
  XXX_____,______XX,X_______,
  XXX_____,_____XXX,X_______,
  XXX_____,____XXXX,________,
  XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXX___,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________,
  XXX_____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDengXian_24_0056[ 69] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXX_____,________,__XXX___,
  XXXX____,________,_XXXX___,
  _XXX____,________,_XXX____,
  _XXX____,________,_XXX____,
  __XXX___,________,XXX_____,
  __XXX___,________,XXX_____,
  __XXX___,________,XXX_____,
  ___XXX__,_______X,XX______,
  ___XXX__,_______X,XX______,
  ___XXXX_,______XX,XX______,
  ____XXX_,______XX,X_______,
  ____XXX_,______XX,X_______,
  _____XXX,_____XXX,________,
  _____XXX,_____XXX,________,
  _____XXX,_____XXX,________,
  ______XX,X___XXX_,________,
  ______XX,X___XXX_,________,
  ______XX,XX_XXXX_,________,
  _______X,XX_XXX__,________,
  _______X,XX_XXX__,________,
  _______X,XXXXXX__,________,
  ________,XXXXX___,________,
  ________,XXXXX___,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDengXian_24_CharInfo[18] = {
   {   8,  29,   2,   6,  11, acGUI_FontDengXian_24_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   8,  29,   1,   6,  11, acGUI_FontDengXian_24_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   3,   3,   3,  26,   9, acGUI_FontDengXian_24_002E } /* code 002E, FULL STOP */
  ,{  16,  23,   1,   6,  18, acGUI_FontDengXian_24_0030 } /* code 0030, DIGIT ZERO */
  ,{   9,  23,   3,   6,  18, acGUI_FontDengXian_24_0031 } /* code 0031, DIGIT ONE */
  ,{  15,  23,   1,   6,  18, acGUI_FontDengXian_24_0032 } /* code 0032, DIGIT TWO */
  ,{  16,  23,   1,   6,  18, acGUI_FontDengXian_24_0033 } /* code 0033, DIGIT THREE */
  ,{  16,  23,   1,   6,  18, acGUI_FontDengXian_24_0034 } /* code 0034, DIGIT FOUR */
  ,{  16,  23,   1,   6,  18, acGUI_FontDengXian_24_0035 } /* code 0035, DIGIT FIVE */
  ,{  16,  23,   1,   6,  18, acGUI_FontDengXian_24_0036 } /* code 0036, DIGIT SIX */
  ,{  15,  23,   2,   6,  18, acGUI_FontDengXian_24_0037 } /* code 0037, DIGIT SEVEN */
  ,{  16,  23,   1,   6,  18, acGUI_FontDengXian_24_0038 } /* code 0038, DIGIT EIGHT */
  ,{  16,  23,   1,   6,  18, acGUI_FontDengXian_24_0039 } /* code 0039, DIGIT NINE */
  ,{  21,  23,   0,   6,  21, acGUI_FontDengXian_24_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  21,  23,   1,   6,  23, acGUI_FontDengXian_24_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  19,  23,   3,   6,  23, acGUI_FontDengXian_24_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  17,  23,   3,   6,  21, acGUI_FontDengXian_24_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  21,  23,   0,   6,  21, acGUI_FontDengXian_24_0056 } /* code 0056, LATIN CAPITAL LETTER V */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_24_Prop7 = {
   0x0056 /* first character */
  ,0x0056 /* last character  */
  ,&GUI_FontDengXian_24_CharInfo[ 17] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_24_Prop6 = {
   0x0050 /* first character */
  ,0x0050 /* last character  */
  ,&GUI_FontDengXian_24_CharInfo[ 16] /* address of first character */
  ,&GUI_FontDengXian_24_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_24_Prop5 = {
   0x0043 /* first character */
  ,0x0044 /* last character  */
  ,&GUI_FontDengXian_24_CharInfo[ 14] /* address of first character */
  ,&GUI_FontDengXian_24_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_24_Prop4 = {
   0x0041 /* first character */
  ,0x0041 /* last character  */
  ,&GUI_FontDengXian_24_CharInfo[ 13] /* address of first character */
  ,&GUI_FontDengXian_24_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_24_Prop3 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontDengXian_24_CharInfo[  3] /* address of first character */
  ,&GUI_FontDengXian_24_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_24_Prop2 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontDengXian_24_CharInfo[  2] /* address of first character */
  ,&GUI_FontDengXian_24_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDengXian_24_Prop1 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontDengXian_24_CharInfo[  0] /* address of first character */
  ,&GUI_FontDengXian_24_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDengXian_24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,36 /* height of font  */
  ,36 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontDengXian_24_Prop1}
  ,29 /* Baseline */
  ,17 /* Height of lowercase characters */
  ,23 /* Height of capital characters */
};

